# Generated by Django 4.2.21 on 2025-07-25 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='job',
        ),
        migrations.RemoveField(
            model_name='application',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='user',
        ),
    ]
