# Generated by Django 4.2.21 on 2025-07-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_remove_application_job_remove_application_job_seeker_and_more'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.jobapplication'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='JobSeeker',
        ),
    ]
