# Generated by Django 4.2.21 on 2025-07-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_alter_message_application_delete_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='approval_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
